surname = input("Введите фамилию")
name = input("Введите имя")
secname = input("Введите отчество")
addres = input("Введите адрес")
print(f"Здравствуйте, {surname.capitalize()} {name.capitalize()} {secname.capitalize()}. Ваш заказ отправлен по адресу {addres.capitalize()}")